{"name": "test_update_user_info[Update User Info - Invalid User ID]", "status": "failed", "statusDetails": {"message": "AssertionError: FAILURE: \u001b[31massert 404 == 400\ntests\\test_api.py:181 in test_update_user_info() -> check.equal(response.status_code,\n\u001b[39m\n------------------------------------------------------------\nFailed Checks: 1", "trace": "FAILURE: \u001b[31massert 404 == 400\ntests\\test_api.py:181 in test_update_user_info() -> check.equal(response.status_code,\n\u001b[39m\n------------------------------------------------------------\nFailed Checks: 1"}, "attachments": [{"name": "log", "source": "c0f59302-9ee7-4c60-89a2-d2762bdc58c6-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "case", "value": "{'Case': 'Update User Info - Invalid User ID', 'Test Type': 'Negative', 'Request_Body': {'firstName': 'jnFdfiGWqBQhijuSMuFFgTNYhS', 'lastName': 'FNHOKvXUcNWcYYRSMFUpDtigEc'}}"}], "start": 1670168779626, "stop": 1670168780434, "uuid": "d66f93b6-4439-48b1-850d-bce5d3141060", "historyId": "671d18b8d9ac583cc0061450fdfb72d2", "testCaseId": "9b22326ca1aa84dd7b5876f09937fe1e", "fullName": "tests.test_api.TestApi#test_update_user_info", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api"}, {"name": "subSuite", "value": "TestApi"}, {"name": "host", "value": "DESKTOP-EGG762M"}, {"name": "thread", "value": "11972-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api"}]}