{"name": "test_get_user_by_id[Get User - Valid User ID1]", "status": "failed", "statusDetails": {"message": "AssertionError: FAILURE: \u001b[31massert False\n +  where False = bool(False)\ntests\\test_api.py:101 in test_get_user_by_id() -> check.is_true(False)  # Fail the test because the response has unexpected json data\n\u001b[39m\n------------------------------------------------------------\nFailed Checks: 1", "trace": "FAILURE: \u001b[31massert False\n +  where False = bool(False)\ntests\\test_api.py:101 in test_get_user_by_id() -> check.is_true(False)  # Fail the test because the response has unexpected json data\n\u001b[39m\n------------------------------------------------------------\nFailed Checks: 1"}, "attachments": [{"name": "log", "source": "fc2a6772-b43f-445f-86f6-8e48f0120da1-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "case", "value": "{'Case': 'Get User - Valid User ID', 'user_id': 'c3e140a4-99db-44c2-a9ea-896904745993', 'is_valid': True}"}], "start": 1670168746035, "stop": 1670168746894, "uuid": "08c320f0-c001-4d55-9aac-4007e566c921", "historyId": "3e258705b6ca799546bdc03dce5f65be", "testCaseId": "0348809fddc28b0397e61969c6de4b71", "fullName": "tests.test_api.TestApi#test_get_user_by_id", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api"}, {"name": "subSuite", "value": "TestApi"}, {"name": "host", "value": "DESKTOP-EGG762M"}, {"name": "thread", "value": "11972-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api"}]}